name: "Docker Configure By WarpBuild"
description: "Configures WarpBuild's Remote Docker Builders"

inputs:
  api-key:
    description: "The API key for the WarpBuild API. This is not required in case of using WarpBuild runners"
    required: false
  profile-name:
    description: "The profile name to use for the WarpBuild Docker Builders"
    required: true
  should-setup-buildx:
    description: "Whether to run setup-buildx automatically or not, if false only the outputs will be returned"
    required: false
    default: "true"
  timeout:
    description: "The timeout(in ms) to wait for the Docker Builders to be ready. By default, it is 5 minutes"
    required: false
    default: "300000"

outputs:
  docker-builder-node-0-endpoint:
    description: "The first Docker builder endpoint."
  docker-builder-node-0-platforms:
    description: "The platforms supported by the first Docker builder."
  docker-builder-node-0-cacert:
    description: "The CA certificate for the first Docker builder."
  docker-builder-node-0-cert:
    description: "The client certificate for the first Docker builder."
  docker-builder-node-0-key:
    description: "The client key for the first Docker builder."
  docker-builder-node-1-endpoint:
    description: "The second Docker builder endpoint (if available)."
  docker-builder-node-1-platforms:
    description: "The platforms supported by the second Docker builder."
  docker-builder-node-1-cacert:
    description: "The CA certificate for the second Docker builder."
  docker-builder-node-1-cert:
    description: "The client certificate for the second Docker builder."
  docker-builder-node-1-key:
    description: "The client key for the second Docker builder."

runs:
  using: 'node20'
  main: 'dist/main.js'
  post: 'dist/cleanup.js'