name: Debug WarpBuild Docker Configure Action

on:
  workflow_dispatch:
    inputs:
      profile-name:
        description: "The profile name to use for the WarpBuild Docker Builders"
        required: true
      runs-on:
        description: "The runner to use for the workflow"
        required: true
        default: "warpdev-ubuntu-latest-x64-2x"
      warp-build-api-domain:
        description: "The API domain to use for the WarpBuild API"
        required: true
        default: "https://api.dev.warpbuild.dev"

env:
  WARPBUILD_API_DOMAIN: ${{ inputs.warp-build-api-domain }}

jobs:
  test:
    name: Debug Run ${{ matrix.run_number }}
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        run_number: [1]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Docker Configure By WarpBuild Action
        id: docker-configure
        uses: ./
        with:
          profile-name: ${{ inputs.profile-name }}
          # api-key: ${{ secrets.WARPBUILD_API_KEY }}
          should-setup-buildx: true

      - name: Print run information
        run: |
          echo "This is parallel run #${{ matrix.run_number }}"
          echo "Using builder endpoint: ${{ steps.docker-configure.outputs.docker-builder-node-0-endpoint }}"

      - name: Build Dockerfile in __tests__ using Buildx
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_CHECKS_ANNOTATIONS: false
        with:
          context: .
          file: __tests__/Dockerfile
          tags: test-image-run-${{ matrix.run_number }}
          load: false
          push: false
          platforms: linux/amd64
