name: Debug Buildx

on:
  push:
    branches:
      - releases/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: remote
          endpoint: tcp://37.27.135.157:30241
        env:
          BUILDER_NODE_0_AUTH_TLS_CACERT: ${{ secrets.WARPBUILD_CA_CERT }}
          BUILDER_NODE_0_AUTH_TLS_CERT: ${{ secrets.WARPBUILD_CERT }}
          BUILDER_NODE_0_AUTH_TLS_KEY: ${{ secrets.WARPBUILD_KEY }}
